<!-- 
    ERIK
	LAST UPDATED: 18 03 30
	MAIL CONTROLLER
-->

<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Mail extends CI_Controller {
    public function __construct()
    {
        parent::__construct();
    }
    public function generateData()
    {
        $sendgridData = new stdClass();

        //Generate personalizations
        $personalizations = array();
        $personalization = new stdClass();
        $to = array();

        $firstReceiver = new stdClass();
        $firstReceiver->email = "evanreusel@gmail.com";
        $firstReceiver->name = "Erik";
        array_push($to, $firstReceiver);
        $personalization->to = $to;
        $bcc = array();
        //TODO: Add foreach for every single email address
        $secondEmail = new stdClass();
        $secondEmail->email = "r0581776@student.thomasmore.be";
        $secondEmail->name = "Erik";
        array_push($bcc, $secondEmail);
        $thirdemail = new stdClass();
        $thirdemail->email = "erik.van.reusel@gmail.com";
        $thirdemail->name = "Erik";
        $personalization->bcc = $bcc;
        array_push($personalizations, $personalization);
        $sendgridData->personalizations = $personalizations;

        //generate Content mail
        $content = array();
        $contentItem = new stdClass();
        $contentItem->type = "text/html";
        $contentItem->value = "SENDGRID MAIL TEST";
        array_push($content, $contentItem);
        $sendgridData->content = $content;
        //generate from object
        $from = new stdClass();
        $from->email = "personeelsfeest@thomasmore.be";
        $from->name = "Personeelsfeest";
        $sendgridData->from = $from;

        return json_encode($sendgridData, JSON_UNESCAPED_SLASHES);
    }
    /**
     * Index Page for this controller.
     *
     * Maps to the following URL
     * 		http://example.com/index.php/welcome
     *	- or -
     * 		http://example.com/index.php/welcome/index
     *	- or -
     * Since this controller is set as the default controller in
     * config/routes.php, it's displayed at http://example.com/
     *
     * So any other public methods not prefixed with an underscore will
     * map to /index.php/welcome/<method_name>
     * @see https://codeigniter.com/user_guide/general/urls.html
     */
    public function send()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $sendgridData = $this->generateData();
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, "https://api.sendgrid.com/v3/mail/send");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $sendgridData);
        curl_setopt($ch, CURLOPT_POST, 1);
        $headers = array();
        $headers[] = "Authorization: Bearer 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";
        $headers[] = "Content-Type: application/json";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        echo $result;

        curl_close ($ch);

    }
}
