<?php

/**
 * Created by PhpStorm.
 * User: erik
 * Date: 19/04/18
 * Time: 23:11
 */
class Mailjet
{
    private $key = "953f6f7ade8e9dde2005d811eee8752b";
    private $secret = "cecefe743a41d7f6ba62444b39127d30";


    private $afzenderEmail = "r0581776@student.thomasmore.be";
    private $afzenderNaam = "Thomas More Events";

    public function maakBerichtObject($ontvangerEmail, $ontvangerNaam, $onderwerp, $inhoud, $inhoudHtml)
    {
        $mail = new stdClass();
        //
        $afzender = new stdClass();
        $afzender->Email = $this->afzenderEmail;
        $afzender->Name = $this->afzenderNaam;
        $mail->From = $afzender;
        //
        $ontvanger = new stdClass();
        $ontvanger->Email = $ontvangerEmail;
        $ontvanger->Name = $ontvangerNaam;
        $mail->To = array($ontvanger);
        $mail->Subject = $onderwerp;
        $mail->TextPart = $inhoud;
        $mail->HtmlPart = $inhoudHtml;
        return $mail;
    }

    public function verstuur($mailJetObject)
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, "https://api.mailjet.com/v3.1/send");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $mailJetObject);

        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_USERPWD, $this->key . ":" . $this->secret);

        $headers = array();
        $headers[] = "Content-Type: application/json";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close ($ch);
        return $result;
    }

}