var annotated_dup =
[
    [ "Admin", "class_admin.html", "class_admin" ],
    [ "Beheer_model", "class_beheer__model.html", "class_beheer__model" ],
    [ "csv_model", "classcsv__model.html", "classcsv__model" ],
    [ "Deelnemer", "class_deelnemer.html", "class_deelnemer" ],
    [ "Jaargang", "class_jaargang.html", "class_jaargang" ],
    [ "Jaargang_model", "class_jaargang__model.html", "class_jaargang__model" ],
    [ "Keuzemogelijkheid", "class_keuzemogelijkheid.html", "class_keuzemogelijkheid" ],
    [ "Keuzemogelijkheid_Model", "class_keuzemogelijkheid___model.html", "class_keuzemogelijkheid___model" ],
    [ "Keuzeoptie", "class_keuzeoptie.html", "class_keuzeoptie" ],
    [ "Keuzeoptie_Model", "class_keuzeoptie___model.html", "class_keuzeoptie___model" ],
    [ "KeuzeOptieVanDeelnemer", "class_keuze_optie_van_deelnemer.html", "class_keuze_optie_van_deelnemer" ],
    [ "KeuzeoptieVanDeelnemer_Model", "class_keuzeoptie_van_deelnemer___model.html", "class_keuzeoptie_van_deelnemer___model" ],
    [ "Mail", "class_mail.html", "class_mail" ],
    [ "Mailherinnering_model", "class_mailherinnering__model.html", "class_mailherinnering__model" ],
    [ "Mailsjabloon_model", "class_mailsjabloon__model.html", "class_mailsjabloon__model" ],
    [ "Main", "class_main.html", "class_main" ],
    [ "Persoon_model", "class_persoon__model.html", "class_persoon__model" ],
    [ "PersoonInHerinnering_model", "class_persoon_in_herinnering__model.html", "class_persoon_in_herinnering__model" ],
    [ "Plaats", "class_plaats.html", "class_plaats" ],
    [ "Plaats_model", "class_plaats__model.html", "class_plaats__model" ],
    [ "Shiften", "class_shiften.html", "class_shiften" ],
    [ "Shiften_Model", "class_shiften___model.html", "class_shiften___model" ],
    [ "Taken", "class_taken.html", "class_taken" ],
    [ "Taken_Model", "class_taken___model.html", "class_taken___model" ],
    [ "Vrijwilliger", "class_vrijwilliger.html", "class_vrijwilliger" ],
    [ "VrijwilligersInShift_Model", "class_vrijwilligers_in_shift___model.html", "class_vrijwilligers_in_shift___model" ]
];